import "server-only";
import crypto from "node:crypto";
import {z} from "zod";
import {getDatabase,repository} from "./store";
import {ActionType,asMinor,minor} from "./domain";

export type ApprovalStatus="PENDING"|"APPROVED"|"REJECTED"|"SNOOZED";
export interface Approval {id:string;caseId:string;customer:string;action:ActionType;amountMinor:string;reason:string;status:ApprovalStatus;version:number;createdAt:string;decidedAt?:string;reviewerNote?:string}
export interface ScheduledJob {id:string;caseId:string;kind:"RETRY"|"PROMISE_DUE"|"CONTACT"|"RECONCILE";dueAt:string;status:"SCHEDULED"|"COMPLETED"|"CANCELLED";attempts:number;lastResult?:string}
export interface ProviderLedgerEntry {id:string;caseId:string;providerPaymentId:string;amountMinor:string;currency:string;confirmedAt:string;providerEventId:string}
export interface OperationsSnapshot {approvals:Approval[];jobs:ScheduledJob[];ledger:ProviderLedgerEntry[];providerConfirmedMinor:string;pendingApprovals:number;scheduledJobs:number;processedProviderEvents:number}

const webhookSchema=z.object({id:z.string().min(3),event:z.string(),created_at:z.number().optional(),payload:z.record(z.string(),z.unknown())}).passthrough();
const approvalDecisionSchema=z.object({decision:z.enum(["APPROVED","REJECTED","SNOOZED"]),expectedVersion:z.number().int().positive(),reviewerNote:z.string().max(300).default("")}).strict();

function initialize(){const db=getDatabase();db.exec(`
CREATE TABLE IF NOT EXISTS approvals (id TEXT PRIMARY KEY, case_id TEXT NOT NULL, customer TEXT NOT NULL, action TEXT NOT NULL, amount_minor TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL, version INTEGER NOT NULL, created_at TEXT NOT NULL, decided_at TEXT, reviewer_note TEXT);
CREATE TABLE IF NOT EXISTS scheduled_jobs (id TEXT PRIMARY KEY, case_id TEXT NOT NULL, kind TEXT NOT NULL, due_at TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_result TEXT);
CREATE TABLE IF NOT EXISTS provider_events (id TEXT PRIMARY KEY, event_type TEXT NOT NULL, received_at TEXT NOT NULL, payload_hash TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS provider_ledger (id TEXT PRIMARY KEY, case_id TEXT NOT NULL, provider_payment_id TEXT NOT NULL UNIQUE, amount_minor TEXT NOT NULL, currency TEXT NOT NULL, confirmed_at TEXT NOT NULL, provider_event_id TEXT NOT NULL UNIQUE);
`);return db}

export function bootstrapOperations(){const run=repository.latest();if(!run)throw new Error("Run the Phase Two portfolio before bootstrapping operations");const db=initialize();const addApproval=db.prepare("INSERT OR IGNORE INTO approvals VALUES (?,?,?,?,?,?,?,?,?,?,?)");const addJob=db.prepare("INSERT OR IGNORE INTO scheduled_jobs VALUES (?,?,?,?,?,?,?)");const created="2026-08-24T10:00:00.000Z";for(const result of run.ai){const item=run.cases.find(c=>c.id===result.caseId)!;if(result.state==="ESCALATED"||minor(item.amountMinor)>5_000_000n)addApproval.run(`APR-${item.id}`,item.id,item.customer,result.selectedAction,item.amountMinor,result.policyReason,"PENDING",1,created,null,null);if(result.promiseStatus)addJob.run(`JOB-PROMISE-${item.id}`,item.id,"PROMISE_DUE","2026-08-28T10:00:00.000Z","SCHEDULED",0,null);else if(result.state!=="RECOVERED"&&result.state!=="CLOSED")addJob.run(`JOB-REVIEW-${item.id}`,item.id,"RECONCILE","2026-08-25T10:00:00.000Z","SCHEDULED",0,null)}return operationsSnapshot()}

export function operationsSnapshot():OperationsSnapshot{const db=initialize();const approvals=db.prepare("SELECT id,case_id caseId,customer,action,amount_minor amountMinor,reason,status,version,created_at createdAt,decided_at decidedAt,reviewer_note reviewerNote FROM approvals ORDER BY created_at,id").all() as Approval[];const jobs=db.prepare("SELECT id,case_id caseId,kind,due_at dueAt,status,attempts,last_result lastResult FROM scheduled_jobs ORDER BY due_at,id").all() as ScheduledJob[];const ledger=db.prepare("SELECT id,case_id caseId,provider_payment_id providerPaymentId,amount_minor amountMinor,currency,confirmed_at confirmedAt,provider_event_id providerEventId FROM provider_ledger ORDER BY confirmed_at DESC").all() as ProviderLedgerEntry[];const count=(db.prepare("SELECT COUNT(*) count FROM provider_events").get() as {count:number}).count;return {approvals,jobs,ledger,providerConfirmedMinor:asMinor(ledger.reduce((s,e)=>s+minor(e.amountMinor),0n)),pendingApprovals:approvals.filter(a=>a.status==="PENDING").length,scheduledJobs:jobs.filter(j=>j.status==="SCHEDULED").length,processedProviderEvents:count}}

export function decideApproval(id:string,input:unknown){const parsed=approvalDecisionSchema.parse(input),db=initialize(),now=new Date().toISOString();const result=db.prepare("UPDATE approvals SET status=?,version=version+1,decided_at=?,reviewer_note=? WHERE id=? AND status='PENDING' AND version=?").run(parsed.decision,now,parsed.reviewerNote,id,parsed.expectedVersion);if(result.changes!==1)throw new Error("Approval is stale or no longer pending");return operationsSnapshot()}

export function runDueJobs(at=new Date().toISOString()){const db=initialize();const due=db.prepare("SELECT id FROM scheduled_jobs WHERE status='SCHEDULED' AND due_at<=?").all(at) as {id:string}[];const update=db.prepare("UPDATE scheduled_jobs SET status='COMPLETED',attempts=attempts+1,last_result='BOUNDED_WAKEUP_RECORDED' WHERE id=? AND status='SCHEDULED'");const tx=db.transaction(()=>due.forEach(j=>update.run(j.id)));tx();return {processed:due.length,snapshot:operationsSnapshot()}}

export function verifyRazorpaySignature(raw:string,signature:string,secret:string){if(!signature||!secret)return false;const expected=crypto.createHmac("sha256",secret).update(raw).digest("hex");const a=Buffer.from(signature,"hex"),b=Buffer.from(expected,"hex");return a.length===b.length&&crypto.timingSafeEqual(a,b)}

function findEntity(payload:Record<string,unknown>,key:string){const value=payload[key] as {entity?:Record<string,unknown>}|undefined;return value?.entity}
export function ingestRazorpayWebhook(raw:string,signature:string,secret:string){if(!verifyRazorpaySignature(raw,signature,secret))throw new Error("Invalid Razorpay webhook signature");const event=webhookSchema.parse(JSON.parse(raw)),db=initialize(),hash=crypto.createHash("sha256").update(raw).digest("hex"),received=new Date().toISOString();const inserted=db.prepare("INSERT OR IGNORE INTO provider_events VALUES (?,?,?,?,?)").run(event.id,event.event,received,hash,raw);if(inserted.changes===0)return {duplicate:true,credited:false,snapshot:operationsSnapshot()};let credited=false;if(["payment.captured","payment_link.paid"].includes(event.event)){const payment=findEntity(event.payload,"payment")??findEntity(event.payload,"payment_link");if(payment){const providerPaymentId=String(payment.id??event.id),amount=String(payment.amount??0),currency=String(payment.currency??"INR"),reference=String(payment.reference_id??(payment.notes as Record<string,unknown>|undefined)?.case_id??"");const match=reference.match(/RC-\d+-\d+/);const caseId=match?.[0]??"UNMATCHED";if(minor(amount)>0n){const ledgerId=`LEDGER-${providerPaymentId}`;credited=db.prepare("INSERT OR IGNORE INTO provider_ledger VALUES (?,?,?,?,?,?,?)").run(ledgerId,caseId,providerPaymentId,amount,currency,received,event.id).changes===1}}}return {duplicate:false,credited,snapshot:operationsSnapshot()}}

export const webhookFixture=(id="evt_recoverai_test")=>({id,event:"payment_link.paid",created_at:Math.floor(Date.now()/1000),payload:{payment_link:{entity:{id:"plink_fixture",amount:799900,currency:"INR",reference_id:"recoverai-RC-2026-002-fixture"}}}});

